GRANT SELECT, DELETE, UPDATE, INSERT ON JAQA02 TO USRREPBI;
GRANT SELECT, DELETE, UPDATE, INSERT ON JAQA03 TO USRREPBI;
GRANT SELECT, DELETE, UPDATE, INSERT ON JAQA04 TO USRREPBI;
GRANT SELECT, DELETE, UPDATE, INSERT ON JAQA05 TO USRREPBI;
GRANT SELECT, DELETE, UPDATE, INSERT ON JAQA06 TO USRREPBI;

GRANT SELECT ON JAQA02 TO CBRAVOA;
GRANT SELECT ON JAQA03 TO CBRAVOA;
GRANT SELECT ON JAQA04 TO CBRAVOA;
GRANT SELECT ON JAQA05 TO CBRAVOA;
GRANT SELECT ON JAQA06 TO CBRAVOA;

GRANT SELECT ON JAQA02 TO SHUANCO;
GRANT SELECT ON JAQA03 TO SHUANCO;
GRANT SELECT ON JAQA04 TO SHUANCO;
GRANT SELECT ON JAQA05 TO SHUANCO;
GRANT SELECT ON JAQA06 TO SHUANCO;