GRANT SELECT,INSERT,UPDATE,DELETE ON BANTPROD_G.JAQA02 TO USRBNDJ;
GRANT SELECT,INSERT,UPDATE,DELETE ON BANTPROD_G.JAQA03 TO USRBNDJ;
GRANT SELECT,INSERT,UPDATE,DELETE ON BANTPROD_G.JAQA04 TO USRBNDJ;
GRANT SELECT,INSERT,UPDATE,DELETE ON BANTPROD_G.JAQA05 TO USRBNDJ;
GRANT SELECT,INSERT,UPDATE,DELETE ON BANTPROD_G.JAQA06 TO USRBNDJ;

GRANT SELECT ON BANTPROD_G.JAQA02 TO SHUANCO;
GRANT SELECT ON BANTPROD_G.JAQA03 TO SHUANCO;
GRANT SELECT ON BANTPROD_G.JAQA04 TO SHUANCO;
GRANT SELECT ON BANTPROD_G.JAQA05 TO SHUANCO;
GRANT SELECT ON BANTPROD_G.JAQA06 TO SHUANCO;

GRANT SELECT ON BANTPROD_G.JAQA02 TO CBRAVOA;
GRANT SELECT ON BANTPROD_G.JAQA03 TO CBRAVOA;
GRANT SELECT ON BANTPROD_G.JAQA04 TO CBRAVOA;
GRANT SELECT ON BANTPROD_G.JAQA05 TO CBRAVOA;
GRANT SELECT ON BANTPROD_G.JAQA06 TO CBRAVOA;
