---------------------------------------------------
----------------- ESTRUCTURA SDT ------------------
---------------------------------------------------

--MORA SBS --
DELETE from BTI026 WHERE BTISDTNOM ='SdtJAQMBBTRESUMENMORASBS';--0
Insert into BTI026 (BTISDTNOM,BTISDTVERSION,BTISDTELEMNOM,BTISDTELEMNINT,BTISDTELEMOBL,BTISDTELEMCAT,BTISDTELEMTIPO,BTISDTELEMSDT,BTISDTELEMSDTVE,BTISDTELEMPLANO,BTISDTELEMLARGO,BTISDTELEMENU,BTISDTELEMVAL,BTISDTELEMDSC,BTISDTELEMPOSI,BTISDTELEMCATIT) values ('SdtJAQMBBTRESUMENMORASBS','1','CantidadCliente','CantidadCliente','S','B','Long',' ',' ',' ',0,'N',' ',' ',3,' ');
Insert into BTI026 (BTISDTNOM,BTISDTVERSION,BTISDTELEMNOM,BTISDTELEMNINT,BTISDTELEMOBL,BTISDTELEMCAT,BTISDTELEMTIPO,BTISDTELEMSDT,BTISDTELEMSDTVE,BTISDTELEMPLANO,BTISDTELEMLARGO,BTISDTELEMENU,BTISDTELEMVAL,BTISDTELEMDSC,BTISDTELEMPOSI,BTISDTELEMCATIT) values ('SdtJAQMBBTRESUMENMORASBS','1','Descripcion','Descripcion','S','B','String',' ',' ',' ',0,'N',' ',' ',2,' ');
Insert into BTI026 (BTISDTNOM,BTISDTVERSION,BTISDTELEMNOM,BTISDTELEMNINT,BTISDTELEMOBL,BTISDTELEMCAT,BTISDTELEMTIPO,BTISDTELEMSDT,BTISDTELEMSDTVE,BTISDTELEMPLANO,BTISDTELEMLARGO,BTISDTELEMENU,BTISDTELEMVAL,BTISDTELEMDSC,BTISDTELEMPOSI,BTISDTELEMCATIT) values ('SdtJAQMBBTRESUMENMORASBS','1','FechaIngreso','FechaIngreso','S','B','String',' ',' ',' ',0,'N',' ',' ',1,' ');
Insert into BTI026 (BTISDTNOM,BTISDTVERSION,BTISDTELEMNOM,BTISDTELEMNINT,BTISDTELEMOBL,BTISDTELEMCAT,BTISDTELEMTIPO,BTISDTELEMSDT,BTISDTELEMSDTVE,BTISDTELEMPLANO,BTISDTELEMLARGO,BTISDTELEMENU,BTISDTELEMVAL,BTISDTELEMDSC,BTISDTELEMPOSI,BTISDTELEMCATIT) values ('SdtJAQMBBTRESUMENMORASBS','1','Monto','Monto','S','B','Double',' ',' ',' ',0,'N',' ',' ',4,' ');
COMMIT;