---------------------------------------------------
--------- PARAMETROS DE LOS METODOS ---------------
---------------------------------------------------

--POSICION DE NEGOCIOS --
DELETE from  BTI019 Where BTINOM ='CMACMISTI' AND BTISRVNOM = 'CMACMoraSBS' AND BTIMTDNOM = 'ObtenerResumenMoraSBS'; -- 0
Insert into BTI019 (BTINOM,BTISRVNOM,BTISRVVER,BTIMTDNOM,BTISRVPARPOSI,BTISRVPARNOM,BTISRVPARNOMJAVA,BTISRVPARDIR,BTISRVVARTIPO,BTISRVPARITTIPO,BTISRVPARVALOR,BTISRVCATIT,BTISRVCAT,BTISRVSDTVER,BTISRVPARLARGO,BTISRVPARLVAL,BTISRVPARITNOM) values ('CMACMISTI','CMACMoraSBS','1','ObtenerResumenMoraSBS',1,'Usuario','param0','I','String',' ',' ','B','B',' ',0,' ',' ');
Insert into BTI019 (BTINOM,BTISRVNOM,BTISRVVER,BTIMTDNOM,BTISRVPARPOSI,BTISRVPARNOM,BTISRVPARNOMJAVA,BTISRVPARDIR,BTISRVVARTIPO,BTISRVPARITTIPO,BTISRVPARVALOR,BTISRVCATIT,BTISRVCAT,BTISRVSDTVER,BTISRVPARLARGO,BTISRVPARLVAL,BTISRVPARITNOM) values ('CMACMISTI','CMACMoraSBS','1','ObtenerResumenMoraSBS',2,'Fecha','param1','O','String',' ',' ','B','B',' ',0,' ',' ');
Insert into BTI019 (BTINOM,BTISRVNOM,BTISRVVER,BTIMTDNOM,BTISRVPARPOSI,BTISRVPARNOM,BTISRVPARNOMJAVA,BTISRVPARDIR,BTISRVVARTIPO,BTISRVPARITTIPO,BTISRVPARVALOR,BTISRVCATIT,BTISRVCAT,BTISRVSDTVER,BTISRVPARLARGO,BTISRVPARLVAL,BTISRVPARITNOM) values ('CMACMISTI','CMACMoraSBS','1','ObtenerResumenMoraSBS',3,'Encabezado','param2','O','String',' ',' ','B','B',' ',0,' ',' ');
Insert into BTI019 (BTINOM,BTISRVNOM,BTISRVVER,BTIMTDNOM,BTISRVPARPOSI,BTISRVPARNOM,BTISRVPARNOMJAVA,BTISRVPARDIR,BTISRVVARTIPO,BTISRVPARITTIPO,BTISRVPARVALOR,BTISRVCATIT,BTISRVCAT,BTISRVSDTVER,BTISRVPARLARGO,BTISRVPARLVAL,BTISRVPARITNOM) values ('CMACMISTI','CMACMoraSBS','1','ObtenerResumenMoraSBS',4,'ResumenMorasSBS','param3','O','Collection','SdtJAQMBBTRESUMENMORASBS',' ','S','C','1',0,' ','SdtJAQMBBTRESUMENMORASBS');
Insert into BTI019 (BTINOM,BTISRVNOM,BTISRVVER,BTIMTDNOM,BTISRVPARPOSI,BTISRVPARNOM,BTISRVPARNOMJAVA,BTISRVPARDIR,BTISRVVARTIPO,BTISRVPARITTIPO,BTISRVPARVALOR,BTISRVCATIT,BTISRVCAT,BTISRVSDTVER,BTISRVPARLARGO,BTISRVPARLVAL,BTISRVPARITNOM) values ('CMACMISTI','CMACMoraSBS','1','ObtenerResumenMoraSBS',5,'Erroresnegocio','param4','S','Collection','SdtsBTErrorNegocio',' ','S','C','1',0,' ','Errornegocio');

COMMIT;