------------------------------------------------------------
-----------------------JAQM06-------------------------------
------------------------------------------------------------
CREATE TABLE "JAQM06" 
   (	"JAQM06CANA" VARCHAR2(2000) NOT NULL ENABLE, 
	"JAQM06COAN" CHAR(10) NOT NULL ENABLE, 
	"JAQM06CACL" NUMBER(10,0), 
	"JAQM06MSBS" NUMBER(17,2), 
	"JAQM06FEIN" DATE, 
	"JAQM06NUM1" NUMBER(10,0), 
	"JAQM06NUM2" NUMBER(10,0), 
	"JAQM06IMP1" NUMBER(17,2), 
	"JAQM06IMP2" NUMBER(17,2), 
	"JAQM06VAR1" VARCHAR2(255), 
	"JAQM06VAR2" VARCHAR2(255), 
	"JAQM06FEC1" DATE, 
	"JAQM06FEC2" DATE
	 ) TABLESPACE BANTPROD_B;

ALTER TABLE JAQM06 ADD PRIMARY KEY ("JAQM06CANA", "JAQM06COAN") USING INDEX TABLESPACE BANTPROD_B_IDX;

COMMENT ON TABLE JAQM06 is 'Mora SBS - Analista';
COMMENT ON COLUMN JAQM06.JAQM06CANA is 'COMITE DEL ANALISTA';
COMMENT ON COLUMN JAQM06.JAQM06COAN is 'CODIGO ANALISTA';
COMMENT ON COLUMN JAQM06.JAQM06CACL is 'CANTIDAD DE CLIENTES';
COMMENT ON COLUMN JAQM06.JAQM06MSBS is 'MORA SBS ACTUAL';
COMMENT ON COLUMN JAQM06.JAQM06FEIN is 'FECHA DE INGRESO';
COMMENT ON COLUMN JAQM06.JAQM06NUM1 is 'AUXILIAR NUMERICO 1';
COMMENT ON COLUMN JAQM06.JAQM06NUM2 is 'AUXILIAR NUMERICO 2';
COMMENT ON COLUMN JAQM06.JAQM06IMP1 is 'AUXILIAR IMPORTE 1';
COMMENT ON COLUMN JAQM06.JAQM06IMP2 is 'AUXILIAR IMPORTE 2';
COMMENT ON COLUMN JAQM06.JAQM06VAR1 is 'AUXILIAR VARCHAR 1';
COMMENT ON COLUMN JAQM06.JAQM06VAR2 is 'AUXILIAR VARCHAR 2';
COMMENT ON COLUMN JAQM06.JAQM06FEC1 is 'AUXILIAR FECHA 1';
COMMENT ON COLUMN JAQM06.JAQM06FEC2 is 'AUXILIAR FECHA 2';

CREATE OR REPLACE PUBLIC SYNONYM JAQM06 FOR BANTPROD.JAQM06;

COMMIT;

------------------------------------------------------------
-----------------------JAQMB6-------------------------------
------------------------------------------------------------
CREATE TABLE "JAQMB6" 
   (	"JAQMB6AGEN" VARCHAR2(30) NOT NULL ENABLE, 
	"JAQMB6COMI" VARCHAR2(2000) NOT NULL ENABLE, 
	"JAQMB6CACL" NUMBER(10,0), 
	"JAQMB6MSBS" NUMBER(17,2), 
	"JAQMB6FEIN" DATE, 
	"JAQMB6NUM1" NUMBER(10,0), 
	"JAQMB6NUM2" NUMBER(10,0), 
	"JAQMB6IMP1" NUMBER(17,2), 
	"JAQMB6IMP2" NUMBER(17,2), 
	"JAQMB6VAR1" VARCHAR2(255), 
	"JAQMB6VAR2" VARCHAR2(255), 
	"JAQMB6FEC1" DATE, 
	"JAQMB6FEC2" DATE 
	 ) TABLESPACE BANTPROD_B;

ALTER TABLE JAQMB6 ADD PRIMARY KEY ("JAQMB6AGEN", "JAQMB6COMI") USING INDEX TABLESPACE BANTPROD_B_IDX;

COMMENT ON TABLE JAQMB6 is 'Mora SBS - Comite';
COMMENT ON COLUMN JAQMB6.JAQMB6AGEN is 'AGENCIA';
COMMENT ON COLUMN JAQMB6.JAQMB6COMI is 'COMITE';
COMMENT ON COLUMN JAQMB6.JAQMB6CACL is 'CANTIDAD DE CLIENTES';
COMMENT ON COLUMN JAQMB6.JAQMB6MSBS is 'MORA SBS ACTUAL';
COMMENT ON COLUMN JAQMB6.JAQMB6FEIN is 'FECHA DE INGRESO';
COMMENT ON COLUMN JAQMB6.JAQMB6NUM1 is 'AUXILIAR NUMERICO 1';
COMMENT ON COLUMN JAQMB6.JAQMB6NUM2 is 'AUXILIAR NUMERICO 2';
COMMENT ON COLUMN JAQMB6.JAQMB6IMP1 is 'AUXILIAR IMPORTE 1';
COMMENT ON COLUMN JAQMB6.JAQMB6IMP2 is 'AUXILIAR IMPORTE 2';
COMMENT ON COLUMN JAQMB6.JAQMB6VAR1 is 'AUXILIAR VARCHAR 1';
COMMENT ON COLUMN JAQMB6.JAQMB6VAR2 is 'AUXILIAR VARCHAR 2';
COMMENT ON COLUMN JAQMB6.JAQMB6FEC1 is 'AUXILIAR FECHA 1';
COMMENT ON COLUMN JAQMB6.JAQMB6FEC2 is 'AUXILIAR FECHA 2';

CREATE OR REPLACE PUBLIC SYNONYM JAQMB6 FOR BANTPROD.JAQMB6;

COMMIT;
------------------------------------------------------------
-----------------------JAQMC6-------------------------------
------------------------------------------------------------
CREATE TABLE "JAQMC6" 
   (	"JAQMC6REGI" VARCHAR2(30) NOT NULL ENABLE, 
	"JAQMC6ZONA" VARCHAR2(40) NOT NULL ENABLE, 
	"JAQMC6AGEN" VARCHAR2(30) NOT NULL ENABLE, 
	"JAQMC6CACL" NUMBER(10,0), 
	"JAQMC6MSBS" NUMBER(17,2), 
	"JAQMC6FEIN" DATE, 
	"JAQMC6NUM1" NUMBER(10,0), 
	"JAQMC6NUM2" NUMBER(10,0), 
	"JAQMC6IMP1" NUMBER(17,2), 
	"JAQMC6IMP2" NUMBER(17,2), 
	"JAQMC6VAR1" VARCHAR2(255), 
	"JAQMC6VAR2" VARCHAR2(255), 
	"JAQMC6FEC1" DATE, 
	"JAQMC6FEC2" DATE 
	) TABLESPACE BANTPROD_B;

ALTER TABLE JAQMC6 ADD PRIMARY KEY ("JAQMC6REGI", "JAQMC6ZONA", "JAQMC6AGEN") USING INDEX TABLESPACE BANTPROD_B_IDX;

COMMENT ON TABLE JAQMC6 is 'Mora SBS - Agencia';
COMMENT ON COLUMN JAQMC6.JAQMC6REGI is 'REGION';
COMMENT ON COLUMN JAQMC6.JAQMC6ZONA is 'ZONA';
COMMENT ON COLUMN JAQMC6.JAQMC6AGEN is 'AGENCIA';
COMMENT ON COLUMN JAQMC6.JAQMC6CACL is 'CANTIDAD DE CLIENTES';
COMMENT ON COLUMN JAQMC6.JAQMC6MSBS is 'MONTOS';
COMMENT ON COLUMN JAQMC6.JAQMC6FEIN is 'FECHA DE INGRESO';
COMMENT ON COLUMN JAQMC6.JAQMC6NUM1 is 'AUXILIAR NUMERICO 1';
COMMENT ON COLUMN JAQMC6.JAQMC6NUM2 is 'AUXILIAR NUMERICO 2';
COMMENT ON COLUMN JAQMC6.JAQMC6IMP1 is 'AUXILIAR IMPORTE 1';
COMMENT ON COLUMN JAQMC6.JAQMC6IMP2 is 'AUXILIAR IMPORTE 2';
COMMENT ON COLUMN JAQMC6.JAQMC6VAR1 is 'AUXILIAR VARCHAR 1';
COMMENT ON COLUMN JAQMC6.JAQMC6VAR2 is 'AUXILIAR VARCHAR 2';
COMMENT ON COLUMN JAQMC6.JAQMC6FEC1 is 'AUXILIAR FECHA 1';
COMMENT ON COLUMN JAQMC6.JAQMC6FEC2 is 'AUXILIAR FECHA 2';

CREATE OR REPLACE PUBLIC SYNONYM JAQMC6 FOR BANTPROD.JAQMC6;


COMMIT;
------------------------------------------------------------
-----------------------JAQMD6-------------------------------
------------------------------------------------------------
CREATE TABLE "JAQMD6" 
   (	"JAQMD6REGI" VARCHAR2(30) NOT NULL ENABLE, 
	"JAQMD6ZONA" VARCHAR2(40) NOT NULL ENABLE, 
	"JAQMD6CACL" NUMBER(10,0), 
	"JAQMD6MSBS" NUMBER(17,2), 
	"JAQMD6FEIN" DATE, 
	"JAQMD6NUM1" NUMBER(10,0), 
	"JAQMD6NUM2" NUMBER(10,0), 
	"JAQMD6IMP1" NUMBER(17,2), 
	"JAQMD6IMP2" NUMBER(17,2), 
	"JAQMD6VAR1" VARCHAR2(255), 
	"JAQMD6VAR2" VARCHAR2(255), 
	"JAQMD6FEC1" DATE, 
	"JAQMD6FEC2" DATE
	 ) TABLESPACE BANTPROD_B;

ALTER TABLE JAQMD6 ADD PRIMARY KEY ("JAQMD6REGI", "JAQMD6ZONA") USING INDEX TABLESPACE BANTPROD_B_IDX;

COMMENT ON TABLE JAQMD6 is 'Mora SBS - Zona';
COMMENT ON COLUMN JAQMD6.JAQMD6REGI is 'REGION';
COMMENT ON COLUMN JAQMD6.JAQMD6ZONA is 'ZONA';
COMMENT ON COLUMN JAQMD6.JAQMD6CACL is 'CANTIDAD DE CLIENTES';
COMMENT ON COLUMN JAQMD6.JAQMD6MSBS is 'MORA SBS ACTUAL';
COMMENT ON COLUMN JAQMD6.JAQMD6FEIN is 'FECHA DE INGRESO';
COMMENT ON COLUMN JAQMD6.JAQMD6NUM1 is 'AUXILIAR NUMERICO 1';
COMMENT ON COLUMN JAQMD6.JAQMD6NUM2 is 'AUXILIAR NUMERICO 2';
COMMENT ON COLUMN JAQMD6.JAQMD6IMP1 is 'AUXILIAR IMPORTE 1';
COMMENT ON COLUMN JAQMD6.JAQMD6IMP2 is 'AUXILIAR IMPORTE 2';
COMMENT ON COLUMN JAQMD6.JAQMD6VAR1 is 'AUXILIAR VARCHAR 1';
COMMENT ON COLUMN JAQMD6.JAQMD6VAR2 is 'AUXILIAR VARCHAR 2';
COMMENT ON COLUMN JAQMD6.JAQMD6FEC1 is 'AUXILIAR FECHA 1';
COMMENT ON COLUMN JAQMD6.JAQMD6FEC2 is 'AUXILIAR FECHA 2';

CREATE OR REPLACE PUBLIC SYNONYM JAQMD6 FOR BANTPROD.JAQMD6;

COMMIT;

------------------------------------------------------------
-----------------------JAQME6-------------------------------
------------------------------------------------------------
CREATE TABLE "JAQME6" 
   (	"JAQME6REGI" VARCHAR2(30) NOT NULL ENABLE, 
	"JAQME6CACL" NUMBER(10,0), 
	"JAQME6MSBS" NUMBER(17,2), 
	"JAQME6FEIN" DATE, 
	"JAQME6NUM1" NUMBER(10,0), 
	"JAQME6NUM2" NUMBER(10,0), 
	"JAQME6IMP1" NUMBER(17,2), 
	"JAQME6IMP2" NUMBER(17,2), 
	"JAQME6VAR1" VARCHAR2(255), 
	"JAQME6VAR2" VARCHAR2(255), 
	"JAQME6FEC1" DATE, 
	"JAQME6FEC2" DATE
	 ) TABLESPACE BANTPROD_B;

ALTER TABLE JAQME6 ADD PRIMARY KEY ("JAQME6REGI") USING INDEX TABLESPACE BANTPROD_B_IDX;

COMMENT ON TABLE JAQME6 is 'Mora SBS - Region';
COMMENT ON COLUMN JAQME6.JAQME6REGI is 'REGION';
COMMENT ON COLUMN JAQME6.JAQME6CACL is 'CANTIDAD DE CLIENTES';
COMMENT ON COLUMN JAQME6.JAQME6MSBS is 'MORA SBS ACTUAL';
COMMENT ON COLUMN JAQME6.JAQME6FEIN is 'FECHA DE INGRESO';
COMMENT ON COLUMN JAQME6.JAQME6NUM1 is 'AUXILIAR NUMERICO 1';
COMMENT ON COLUMN JAQME6.JAQME6NUM2 is 'AUXILIAR NUMERICO 2';
COMMENT ON COLUMN JAQME6.JAQME6IMP1 is 'AUXILIAR IMPORTE 1';
COMMENT ON COLUMN JAQME6.JAQME6IMP2 is 'AUXILIAR IMPORTE 2';
COMMENT ON COLUMN JAQME6.JAQME6VAR1 is 'AUXILIAR VARCHAR 1';
COMMENT ON COLUMN JAQME6.JAQME6VAR2 is 'AUXILIAR VARCHAR 2';
COMMENT ON COLUMN JAQME6.JAQME6FEC1 is 'AUXILIAR FECHA 1';
COMMENT ON COLUMN JAQME6.JAQME6FEC2 is 'AUXILIAR FECHA 2';

CREATE OR REPLACE PUBLIC SYNONYM JAQME6 FOR BANTPROD.JAQME6;

COMMIT;